openapi: 3.0.0
info:
  title: TickFund API Gateway
  description: blah blah
  version: 0.0.2

servers:
  - url: http://localhost
    description: Development server

paths:
  /transactions:
    post:
      summary: Allow client to test for connection
      responses:
        200:
          description: Connect successfully
        default:
          description: An error has occurred

  /coins:
    get:
      summary: Get list of supported Coin or Coin's info
      responses:
        200:
          description: Fetch supported list successfully
          content:
            application/json:
              schema:
                type: array
                items:
        500:
          description: Internal Server Error

  /coins/{code}:
    get:
      summary: Get info about Coin
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
            example: "ETH"
      responses:
        200:
          description: Get info of Coin successfully
          content:
            application/json:
              schema:
        404:
          description: Coin not found
        500:
          description: Internal Server Error
