version: '3.8'
services:
  auth_service:
    container_name: auth_service
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:8082
    volumes:
      - media:./media

  file_service:
    container_name: file_service
    build:
      context: ./file-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 6000:6000

volumes:
  media: