version: '3.8'
services:
  auth_service:
    container_name: auth_service
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:8082

  file_service:
    container_name: file_service
    build:
      context: ./file-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3002:3002
    volumes:
      - media:/usr/src/app/auth_service/media
      
  tickfund_service:
    image: tickfund_service
    container_name: tickfund_service
    restart: always
    ports:
      - 8081:8081

  tickfund_application:
    build:
      context: ./ReactApp
      dockerfile: Dockerfile
    container_name: tickfund_application
    restart: always
    ports:
      - 3000:3000

volumes:
  media: