FROM nginx
COPY api_conf.d/            etc/nginx/
COPY api_backends.conf      etc/nginx/
COPY api_gateway.conf       etc/nginx/
COPY api_json_errors.conf   etc/nginx/
COPY conf.d/                etc/nginx/
COPY nginx.conf             etc/nginx/
