version: '3.9'
services:
### MySQL Container
    mysql:
        image: mysql
        volumes:
            - db:/var/lib/mysql
        restart: always
        # environment:
        #     - MYSQL_DATABASE=${MYSQL_DATABASE}
        #     - MYSQL_USER=${MYSQL_USER}
        #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        env_file: .env
        ports:
            - "3306:3306"
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    db:
        name: db