version: '3.9'
services:
### MySQL Container
    mysql:
        image: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - db:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d
        restart: always
        environment:
        #     - MYSQL_DATABASE=${MYSQL_DATABASE}
        #     - MYSQL_USER=${MYSQL_USER}
        #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_PASSWORD: root
        env_file: .env
        ports:
            - "3306:3306"
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    db:
        name: db