openapi: 3.0.0
info:
  title: TickFund API Gateway
  description: blah blah
  version: 0.0.2

servers:
  - url: http://localhost
    description: Development server

paths:
  /transactions/new:
    post:
      summary: Add a new transaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewTransactionData"
      responses:
        200:
          description: New Transaction successfully added
        400:
          description: Not Found
        500:
          description: Internal Server Error
  
  /transactions/{id}:
    get:
      summary: Get a transaction data by given ID
      parameters:
        - in: path
          name: id   # Note the name is the same as in the path
          required: true
          schema:
            type: string
            example: "#1d34ae"
          description: Transaction ID
      responses:
        200:
          description: New Category successfully added
        400:
          description: Not Found
        500:
          description: Internal Server Error

  /categories/new:
    post:
      summary: Add a new category
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: New Category successfully added
        400:
          description: Not Found
        500:
          description: Internal Server Error
  
  /categories/delete/{name}:
    delete:
      summary: Delete an exist category
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            example: "Tien dien"
          description: Ten danh muc
      responses:
        200:
          description: Success
        400:
          description: Not Found
        500:
          description: Internal Server Error

components:
  schemas:
    Category:
      type: object
      properties:
        name:
          type: string
          example: Tiền điện
        type:
          type: string
          enum: [Thu, Chi]
          example: Thu

    NewTransactionData:
      type: object
      properties:
        amount:
          type: integer
          format: int64
          example: 300 000
        category:
          $ref: "#/components/schemas/Category"
        userID:
          type: string
          example: 1915940
        note:
          type: string
          example: "Tien dien thang 4"
        attachments:
          type: string
          format: binary
          example: tiendien.jpg

    TransactionData:
      type: object
      properties:
        id:
          type: string
          example: "#10ac6we"
        category:
          $ref: "#/components/schemas/Category"
        userID:
          type: string
          example: 1915940
        note:
          type: string
          example: "Tien dien thang 4"
        attachments:
          type: string
          format: binary
          example: tiendien.jpg

    Person:
      type: object
      properties:
        id:
          type: string
          example: 1915940
        name:
          type: string
          example: Cu Do Thanh Nhan
        username:
          type: string
          example: "@nhan2k1"
        avatar:
          type: string
          format: byte
          example: "nhan.jpg"