openapi: 3.0.0
info:
  title: TickFund API Gateway
  description: blah blah
  version: 0.0.2

servers:
  - url: http://localhost:3000
    description: Development url
  - url: https://api.tickfund.com/v1
    description: API Gateway
  - url: https://cdn.tickfund.com/
    description: Transfer files for system

tags:
  - name: transactions
    description: API for transactions
  - name: categories
    description: API for categories
  - name: plannings
    description: API for plannings
  - name: satistics
    description: API for satistics

paths:
  # TRANSACTION
  /transactions/new:
    post:
      summary: Add a new transaction
      tags:
        - transactions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewTransactionData"
      responses:
        200:
          description: New Transaction successfully added
        400:
          description: Not Found
        500:
          description: Internal Server Error

  /transactions/{id}:
    get:
      summary: Get more detail (notes and attachments) of a transaction by given ID
      tags:
        - transactions
      parameters:
        - in: path
          name: id # Note the name is the same as in the path
          required: true
          schema:
            type: string
            example: "#1d34ae"
          description: Transaction ID
      responses:
        200:
          description: New Category successfully added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDetailData"
        400:
          description: Not Found
        500:
          description: Internal Server Error

  /transactions/history:
    get:
      summary: Get transaction list by some pre-condition
      tags:
        - transactions
      parameters:
        - in: query
          name: query
          schema:
            $ref: "#/components/schemas/Query"
            default: {}
          required: false
          description: Object of conditions
      responses:
        200:
          description: Retrieve successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TransactionData"
        400:
          description: Not Found
        500:
          description: Internal Server Error
  
  # CATEGORIES
  /categories/new:
    post:
      summary: Add a new category
      tags:
        - categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: New Category successfully added
        400:
          description: Not Found
        500:
          description: Internal Server Error

  /categories/delete/{name}:
    delete:
      summary: Delete an exist category
      tags:
        - categories
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            example: "Tien dien"
          description: Ten danh muc
      responses:
        200:
          description: Success
        400:
          description: Not Found
        500:
          description: Internal Server Error
  
  /categories/edit/{name}:
    put:
      summary: Edit a category name
      tags:
        - categories
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            example: "Tien dien"
          description: Ten danh muc
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                newName:
                  type: string
                  example: "Tien dien moi"
      responses:
        200:
          description: Success
        400:
          description: Not Found
        500:
          description: Internal Server Error

  /categories:
    get:
      summary: Get all categories
      tags:
        - categories
      responses:
        200:
          description: Success
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"


        400:
          description: Not Found
        500:
          description: Internal Server Error

  # PLANNING
  /plannings/new:
    post:
      summary: Add a new planning
      tags:
        - plannings
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewTransactionData"
      responses:
        200:
          description: New Transaction successfully added
        400:
          description: Not Found
        500:
          description: Internal Server Error

  /plannings/{id}:
    get:
      summary: Get more detail (notes and attachments) of a transaction by given ID
      tags:
        - plannings
      parameters:
        - in: path
          name: id # Note the name is the same as in the path
          required: true
          schema:
            type: string
            example: "#1d34ae"
          description: Transaction ID
      responses:
        200:
          description: New Category successfully added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDetailData"
        400:
          description: Not Found
        500:
          description: Internal Server Error

  /plannings/history:
    get:
      summary: Get transaction list by some pre-condition
      tags:
        - plannings
      parameters:
        - in: query
          name: query
          schema:
            $ref: "#/components/schemas/Query"
            default: {}
          required: false
          description: Object of conditions
      responses:
        200:
          description: Retrieve successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TransactionData"
        400:
          description: Not Found
        500:
          description: Internal Server Error

components:
  schemas:
    Category:
      type: object
      properties:
        name:
          type: string
          example: Tiền điện
        type:
          type: string
          enum: [Thu, Chi]
          example: Thu

    NewTransactionData:
      type: object
      description: Data format for create a new transaction
      properties:
        amount:
          type: integer
          format: int64
          example: 300 000
        category:
          $ref: "#/components/schemas/Category"
        userID:
          type: string
          example: 1915940
        note:
          type: string
          example: "Tien dien thang 4"
        attachments:
          type: string
          format: binary
          example: tiendien.jpg

    TransactionData:
      type: object
      description: Data for displaying a transaction on table
      properties:
        id:
          type: string
          example: "#10ac6we"
        user:
          $ref: "#/components/schemas/Person"
        time:
          type: string
          example: "2022/03/30 06:24:24"
        amount:
          type: number
          example: 300000
        category:
          $ref: "#/components/schemas/Category"
        
        
    
    TransactionDetailData:
      type: object
      description: Get more details of a transaction
      properties:
        note:
          type: string
          example: "Tien dien thang 4"
        attachments:
          type: array
          format: url
          example: [ "tiendien.jpg", "anh_giao_dich.png" ]

    Person:
      type: object
      description: Display basic personal data of a user
      properties:
        id:
          type: string
          example: 1915940
        name:
          type: string
          example: Cu Do Thanh Nhan
        username:
          type: string
          example: "@nhan2k1"
        avatar:
          type: string
          example: "https://cdn.ticklab.com"
          format: byte

    Query:
      type: object
      properties:
        offset:
          type: integer
          default: 0
        limit:
          type: integer
          default: 20
        sort:
          type: string
          enum: ["asc", "desc"]
          default: "desc"
        search:
          type: string
          example: "Tien nha"
        filter:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: 'amount'
              op:
                type: string
                enum: ['<', '>', '==', '...']
              rhs:
                type: object
                properties:
                  type:
                    type: string
                    example: 'datetime'
                  value:
                    type: string
                    example: '2022-10-05 15:30'

  
      
        

