openapi: 3.0.0
info:
  title: TickFund API Gateway
  description: blah blah
  version: 0.0.2

servers:
  - url: http://localhost:3000
    description: Development url
  - url: https://api.tickfund.com/v1
    description: API Gateway
  - url: https://cdn.tickfund.com/
    description: Transfer files for system

tags:
  - name: transactions
    description: API for transactions
  - name: categories
    description: API for categories
  - name: plannings
    description: API for plannings
  - name: satistics
    description: API for satistics
  

paths:
  /transactions/new:
    post:
      summary: Add a new transaction
      tags:
        - transactions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewTransactionData"
      responses:
        200:
          description: New Transaction successfully added
        400:
          description: Not Found
        500:
          description: Internal Server Error
  
  /transactions/{id}:
    get:
      summary: Get more detail (notes and attachments) of a transaction by given ID
      tags:
        - transactions
      parameters:
        - in: path
          name: id   # Note the name is the same as in the path
          required: true
          schema:
            type: string
            example: "#1d34ae"
          description: Transaction ID
      responses:
        200:
          description: New Category successfully added
        400:
          description: Not Found
        500:
          description: Internal Server Error

  /categories/new:
    post:
      summary: Add a new category
      tags:
        - categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: New Category successfully added
        400:
          description: Not Found
        500:
          description: Internal Server Error
  
  /categories/delete/{name}:
    delete:
      summary: Delete an exist category
      tags:
        - categories
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            example: "Tien dien"
          description: Ten danh muc
      responses:
        200:
          description: Success
        400:
          description: Not Found
        500:
          description: Internal Server Error
  
  /categories/edit/{name}:
    put:
      summary: Edit a category name
      tags:
        - categories
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
            example: "Tien dien"
          description: Ten danh muc
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                newName:
                  type: string
                  example: "Tien dien moi"
      responses:
        200:
          description: Success
        400:
          description: Not Found
        500:
          description: Internal Server Error

  /categories:
    get:
      summary: Get all categories
      tags:
        - categories
      responses:
        200:
          description: Success
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"


        400:
          description: Not Found
        500:
          description: Internal Server Error
components:
  schemas:
    Category:
      type: object
      properties:
        name:
          type: string
          example: Tiền điện
        type:
          type: string
          enum: [Thu, Chi]
          example: Thu

    NewTransactionData:
      type: object
      description: Data format for create a new transaction
      properties:
        amount:
          type: integer
          format: int64
          example: 300 000
        category:
          $ref: "#/components/schemas/Category"
        userID:
          type: string
          example: 1915940
        note:
          type: string
          example: "Tien dien thang 4"
        attachments:
          type: string
          format: binary
          example: tiendien.jpg

    TransactionData:
      type: object
      description: Data for displaying a transaction on table
      properties:
        id:
          type: string
          example: "#10ac6we"
        category:
          $ref: "#/components/schemas/Category"
        user:
          $ref: "#/components/schemas/Person"
        note:
          type: string
          example: "Tien dien thang 4"
        attachments:
          type: array
          format: url
          example: [ "tiendien.jpg", "anh_giao_dich.png" ]
    
    TransactionDetailData:
      type: object
      description: Get more details of a transaction
      properties:
        attachments:
          type: array
          example: []

    Person:
      type: object
      description: Display basic personal data of a user
      properties:
        id:
          type: string
          example: 1915940
        name:
          type: string
          example: Cu Do Thanh Nhan
        username:
          type: string
          example: "@nhan2k1"
        avatar:
          type: string
          example: "https://cdn.ticklab.com"